#!/usr/bin/env bash

trap "_clean" EXIT

_clean() {
rm -rf /tmp/$$_*
}

function INFOF() {
echo -en "\033[33m $@: \033[0m"
# echo -en "$@: "
}

function INFO() {
echo -e "\033[33m $@ \033[0m"
}

function CMDF() {
echo -en "\033[32m $@ \033[0m"
}

function CMD() {
echo -e "\033[32m $@ \033[0m"
# echo -e "$@"
}


export BASEPATH=`dirname $(readlink -f ${BASH_SOURCE[0]})`
export -f INFO INFOF CMD CMDF
name="$1"

function usage() {
echo "DOC 查看自己常用的命令"
echo
echo "Usage: "
echo "  doc [COMMAND] ..."
echo "  doc pull: 从 gihub 仓库拉最新文档"
echo "  doc push: 推送最新文档到 gihub 仓库"
echo "  doc --help"
echo "[COMMAND]: "
ls "$BASEPATH"'/docs' | while read line
do
echo "  $line"
done
}

function pullToLocal() {
git clone git@github.com:Xiechengqi/docForLinux.git /tmp/$$_repo
cp -f /tmp/$$_repo/docs/* /opt/doc/docs
}

function pushToGithub() {
git clone git@github.com:Xiechengqi/docForLinux.git /tmp/$$_repo
cd /tmp/$$_repo
cp -f /opt/doc/docs/* docs/
git add -A && git commit -m 'add docs' && git push origin main
cd -
}

function print() {
[ "$1" == "pull" ] && pullToLocal && return 0
[ "$1" == "push" ] && pushToGithub && return 0
ls "$BASEPATH"'/docs' | grep "$1" &>/dev/null
[ $? -ne 0 ] && echo -e "\033[31m $1 does not exist ... \033[0m" && return 0
echo '>>> '"$1"
cat "$BASEPATH"'/docs/'"$1" | while read line
do
INFOF $(echo $line | awk -F ':' '{print $1}')
CMD $(echo $line | awk -F ': ' '{$1=null;print $0}') 
done
}

[ $# = 0 ] && usage
while [ $# != 0 ]
do
print $1 || true
shift
done
